name: zion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.9
  persistent_bottom_nav_bar: ^1.2.1
  intl: ^0.16.1
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.6+1
  cached_network_image: ^2.0.0-rc
  fluttertoast: ^4.0.1
  expansion_tile_card: ^1.0.3
  shimmer: ^1.1.1
  badges: ^1.1.1

  app_settings: ^3.0.1
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.3+4
  photo_view: ^0.9.2
  image_cropper: ^1.2.1

  provider: ^4.0.1
  equatable: ^1.1.1
  flutter_parsed_text: ^1.1.0
  uuid: ^2.0.1
  transparent_image: ^1.0.0

  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.1.4
  firebase_storage: ^3.1.3
  firebase_database: ^3.1.3
  onesignal_flutter: ^2.3.4
  timeago: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter

  settings_ui:
    git:
      url: git://github.com/Aanu1995/flutter-settings-ui.git
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
